In [85]:
import os

os.chdir("..")

In [86]:
import pandas as pd

In [3]:
# Load data
df = pd.read_pickle("data/processed/reports_tokenized.p")
df

ID Identifier                         Company_Name          ISIN  \
0        0      888.L                     888 Holdings PLC  GI000A0F6407   
1        1        A.N             Agilent Technologies Inc  US00846U1016   
2        2       AA.N                           Alcoa Corp  US0138721065   
3        3     AAC.AX  Australian Agricultural Company Ltd  AU000000AAC9   
4        4      AAF.L                    Airtel Africa PLC  GB00BKDRYJ47   
...    ...        ...                                  ...           ...   
8098  8098        Z.O                     Zillow Group Inc  US98954M2008   
8099  8099      ZBH.N           Zimmer Biomet Holdings Inc  US98956P1021   
8100  8100      ZBH.N           Zimmer Biomet Holdings Inc  US98956P1021   
8101  8101      ZBH.N           Zimmer Biomet Holdings Inc  US98956P1021   
8102  8102      ZBH.N           Zimmer Biomet Holdings Inc  US98956P1021   

     Ticker       Country_of_Exchange  Financial_Period_Absolute  \
0       888            United Kingdom                       2020   
1         A  United States of America                       2020   
2        AA  United States of America                       2020   
3       AAC                 Australia                       2021   
4       AAF            United Kingdom                       2020   
...     ...                       ...                        ...   
8098      Z  United States of America                       2018   
8099    ZBH  United States of America                       2018   
8100    ZBH  United States of America                       2017   
8101    ZBH  United States of America                       2016   
8102    ZBH  United States of America                       2015   

     Financial_Period_Relative  \
0                          FY0   
1                          FY0   
2                          FY0   
3                          FY0   
4                          FY0   
...                        ...   
8098                      FY-2   
8099                      FY-2   
8100                      FY-3   
8101                      FY-4   
8102                      FY-5   

                                                CSR_URL  SDG_1  ...  SDG_12  \
0     https://corporate.888.com/wp-content/uploads/2...  False  ...    True   
1     https://www.agilent.com/about/companyinfo/sust...  False  ...    True   
2     https://www.alcoa.com/sustainability/en/pdf/20...  False  ...    True   
3     https://aaco.com.au/wp-content/uploads/2021/07...  False  ...   False   
4     https://airtel.africa/assets/pdf/Airtel_Africa...   True  ...    True   
...                                                 ...    ...  ...     ...   
8098  https://www.responsibilityreports.com/HostedDa...  False  ...   False   
8099  https://www.responsibilityreports.com/HostedDa...  False  ...    True   
8100  https://www.responsibilityreports.com/HostedDa...  False  ...    True   
8101  https://www.responsibilityreports.com/HostedDa...  False  ...    True   
8102  https://www.responsibilityreports.com/HostedDa...  False  ...    True   

      SDG_13  SDG_14  SDG_15  SDG_16  SDG_17          CSR_Filename  \
0       True     NaN   False    True   False      0_888.L_2020.pdf   
1       True     NaN    True    True   False        1_A.N_2020.pdf   
2       True     NaN    True    True   False       2_AA.N_2020.pdf   
3       True     NaN   False   False   False     3_AAC.AX_2021.pdf   
4       True     NaN    True    True    True      4_AAF.L_2020.pdf   
...      ...     ...     ...     ...     ...                   ...   
8098   False     NaN   False   False   False    12673_Z.O_2018.pdf   
8099   False     NaN   False    True   False  12674_ZBH.N_2018.pdf   
8100   False     NaN   False    True   False  12675_ZBH.N_2017.pdf   
8101   False     NaN   False    True   False  12676_ZBH.N_2016.pdf   
8102   False     NaN   False   False   False  12677_ZBH.N_2015.pdf   

                                               CSR_Text  \
0     888 HOLDINGS P

In [6]:
df['CSR_Text_clean'][0].split('. ')

['888 ORG ANNUAL REPORT & ACCOUNTS 2020 A YEAR OF STRONG GROWTH ORG IS ONE OF THE WORLDS LEADING ONLINE BETTING AND GAMING COMPANIES',
 'ORG ORG (888 or the ORG) and its subsidiaries (together, the ORG) operate leading online gaming brands across four key product verticals (ORG) with a presence across multiple regulated markets',
 '888S MISSION 888s mission is to develop state-of-the-art technology and products that provide fun, fair and safe digital gambling products to players globally',
 'ORG leverages its proprietary technology to provide to players and B2B partners an innovative and world-class online gambling experience',
 'By doing this effectively, ORG is able to succeed in the fast-growing and dynamic online gambling industry and generate value for its shareholders',
 '888S FOCUS 888s primary strategic focus is on growing its strong brands in sustainable markets where there are regulatory frameworks that protect customers and provide clarity for operators',
 'To achieve this, 

## Universal sentence encoder

In [87]:
#@title Load the Universal Sentence Encoder's TF Hub module
#from absl import logging

import tensorflow as tf
import tensorflow_hub as hub
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import re
import seaborn as sns

model = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
def embed(input):
    return model(input)

In [88]:
sdg1 = [
    "social",
    "end poverty",
    "poverty dimension",
    "poverty",
    "social protection",
    "poor",
    "unemployed person",
    "poverty line",
    "protection",
    "cash benefit",
    "extreme poverty",
    "poor vulnerable",
    "humanitarian",
    "vulnerable",
]
sdg2 = [
    "malnutrition",
    "hunger",
    "food producer",
    "underweight",
    "hunger malnutrition",
    "undernutrition",
    "famine",
    "food insecurity",
    "agricultural productivity",
    "agricultural",
    "extreme hunger",
    "agriculture",
    "prevalence undernourishment",
    "nutritional need",
    "food",
]
sdg3 = [
    "life expectancy",
    "mental health",
    "air pollution",
    "medicine vaccine",
    "infectious disease",
    "good health",
    "respiratory disease",
    "reproductive health",
    "mortality",
    "healthcare",
    "disease diabetes",
    "disease",
    "health coverage",
    "health",
    "maternal mortality",
    "death preventable",
    "cardiovascular disease",
]
sdg4 = [
    "teacher",
    "secondary school",
    "proficiency level",
    "primary school",
    "inclusive",
    "literacy",
    "literacy numeracy",
    "higher education",
    "quality education",
    "school",
    "effective learn",
    "vocational train",
    "level proficiency",
    "minimum proficiency",
    "technical vocational",
]
sdg5 = [
    "domestic work",
    "right",
    "sexual violence",
    "woman",
    "girl",
    "discrimination",
    "reproductive health",
    "managerial position",
    "woman girl",
    "marriage",
    "woman representation",
    "gender equality",
    "gender parity",
    "child marriage",
    "gender",
]
sdg6 = [
    "water sanitation",
    "drink water",
    "sanitation",
    "basic drink",
    "wastewater",
    "water scarcity",
    "hygiene",
    "water",
    "sanitation service",
    "sanitation hygiene",
    "supply freshwater",
    "handwash facility",
    "resource management",
    "water stress",
]
sdg7 = [
    "energy",
    "technology",
    "renewable energy",
    "infrastructure",
    "electricity",
    "cheap energy",
    "solar",
    "solar power",
    "wind power",
    "thermal power",
    "energy productivity",
    "energy efficiency",
    "greenhouse gases",
    "greenhouse",
    "fossil fuels",
    "pollution",
    "energy standards",
    "energy access",
    "energy consumption",
    "access electricity",
    "without electricity",
    "fuel technology",
    "fossil fuel",
]
sdg8 = [
    "labor",
    "employment",
    "gdp",
    "job",
    "unemployed",
    "economic growth",
    "productivity",
    "job creation",
    "slavery",
    "forced labor",
    "labor force",
    "women participation",
    "labor organization",
    "human right",
    "informal employment",
    "growth rate",
    "labour productivity",
    "decent work",
    "secure work",
    "global economic",
    "gender pay",
    "crisis level",
    "rate real",
    "decent work",
    "education employment",
    "slavery human",
    "child labour",
    "youth employment",
]
sdg9 = [
    "research development",
    "development",
    "industry",
    "infrastructure",
    "transport",
    "technological progress",
    "communication technology",
    "sustainable development",
    "sustainable industries",
    "innovation",
    "entrepreneurship",
    "access information",
    "access internet",
    "material footprint",
    "develop country",
    "least develop",
    "economic infrastructure",
    "infrastructure support",
    "global manufacture",
    "scientific research",
    "resilient infrastructure",
    "research innovation",
]
sdg10 = [
    "income",
    "population",
    "income inequality",
    "economic inclusion",
    "safe migration",
    "economic inequality",
    "reduce inequality",
    "wealth share",
    "indigenous rights",
    "migrant worker",
    "migrant",
    "official development",
    "income inequality",
    "migration mobility",
    "global wealth",
    "least develop",
    "development assistance",
]
sdg11 = [
    "city",
    "urban",
    "urban population",
    "public",
    "disability",
    "disaster",
    "sustainable city",
    "affordable housing",
    "housing access",
    "resilient societies",
    "public transport",
    "public spaces",
    "urban planning",
    "inclusive",
    "business opportunities",
    "sustainable development",
    "person disability",
    "green public",
    "sustainable resilient",
    "sustainable urbanization",
    "population convenient",
    "convenient access",
]
sdg12 = [
    "responsible consumption",
    "sustainable development",
    "resources",
    "consumption",
    "production",
    "development",
    "reduce waste",
    "efficient",
    "efficient economy",
    "energy consumption",
    "energy efficient",
    "supporting developing",
    "material footprint",
    "natural resource",
    "recycle",
    "sustainable consumption",
    "domestic material",
    "consumption production",
    "food waste",
]
sdg13 = [
    "climate",
    "develop",
    "disaster",
    "local",
    "emissions reductions",
    "global warm",
    "climate change",
    "climate system",
    "greenhouse gas",
    "emissions",
    "co2 emissions",
    "low carbon",
    "disaster risk",
    "sustainable management",
    "natural resource",
    "sea levels",
    "sustainable energy",
    "paris agreement",
    "sustainable energy",
    "climate relate",
    "green climate",
    "disaster risk",
]
sdg14 = [
    "marine",
    "ocean",
    "fish",
    "sea",
    "water",
    "fishery",
    "overfishing",
    "coastal biodiversity",
    "coastal ecosystems",
    "ocean resources" "marine biodiversity",
    "fish stocks",
    "marine pollution",
    "ocean acidification",
    "depleted fisheries",
    "unregulated fish",
    "fish stock",
    "fishery management",
    "marine coastal",
    "fishery subsidy",
    "conservation sustainable",
    "marine technology",
]
sdg15 = [
    "land degradation",
    "terrestrial freshwater",
    "ecosystem",
    "deforestation",
    "specie animal",
    "forest management",
    "biodiversity",
    "conservation",
    "protect area",
    "forest",
    "terrestrial",
    "species",
    "wildlife",
    "protect",
    "agriculture",
    "land",
    "area",
]
sdg16 = [
    "law",
    "human right",
    "right violation",
    "insecurity",
    "institution",
    "violence",
    "exploitation",
    "global governance",
    "transparency",
    "rule",
    "corruption bribery",
    "access justice",
    "corruption",
    "justice",
    "peace",
    "conflict violence",
    "international",
    "victim human",
    "conflict",
]
sdg17 = [
    "sustainable development",
    "innovation",
    "enhance international",
    "official development",
    "capacity build",
    "development",
    "coordinate policy",
    "develop country",
    "assistance",
    "cooperation",
    "international support",
    "international cooperation",
    "partnership",
    "international",
    "policy coherence",
    "development assistance",
    "country",
]

keywords = sdg1 + sdg2 + sdg3 + sdg4 + sdg5 + sdg6 + sdg7 + sdg8 + sdg9 + sdg10 + sdg11 + sdg12 + sdg13 + sdg14 + sdg15 + sdg16 + sdg17
words = ''
for word in keywords:
    words += word + ' '
unique_words = ''
for word in set(words.split(' ')):
    unique_words += word + ' '
unique_words
target_embedding = embed([unique_words])

In [89]:
similarities = []
for sentence in sentences:
    embedding = embed([sentence])
    similarity = cosine_similarity(embedding, target_embedding)
    similarities.append(similarity)

KeyboardInterrupt: 

In [90]:
unique_words

'warm  ocean poor species nutritional agriculture access corruption climate protect coverage right technical service violence death supporting reductions literacy transport basic information coastal law bribery freshwater indigenous learn justice green forced resourcesmarine train growth organization thermal resources ecosystems life cooperation material diabetes women humanitarian enhance effective level consumption capacity unemployed work carbon stress position biodiversity line energy school overfishing gdp numeracy worker policy share undernourishment planning development supply responsible degradation spaces change dimension primary rate gas deforestation wealth safe entrepreneurship job disability expectancy societies prevalence gender slavery wind woman proficiency migration research inequality gases productivity good maternal handwash participation renewable famine city depleted air power convenient agricultural medicine social build internet hunger stocks producer vaccine bus

In [83]:
# Most important sentences
[(x,y) for y, x in sorted(zip(similarities, sentences), reverse=True)]

[("Source: H2 ORG, February 2021 2020* US$ million 2025* US$ million 36,508 20,168 3719 2,540 74,569 60,704 30,503 3,914 2,796 117,368 ORG Annual Report & Accounts 2020 STRATEGIC REPORT GOVERNANCE GOVERNANCE FINANCIAL STATEMENTS FINANCIAL STATEMENTS REVENUE INCREASE BY GEOGRAPHICAL MARKET UK Italy Spain +63% +69% +11% US and Americas +81% FINANCIAL HIGHLIGHTS Revenue-Our overall revenue1 US$ million 560.3 376.7 359.3 42.7 90.0 +52% 849.7 +49% 562.8 +63% 586.8 +48% 63.1 +36% 122.1 +69% 155.6 92.1 59.9 +104% 122.0 2020 2019 2020 2019 2020 2019 2020 2019 2020 2019 2020 2019 2020 2019 Gross profit US$ million Revenue-B2C Casino US$ million Revenue-B2C Poker US$ million Revenue-B2C Sport US$ million Adjusted EBITDA US$ million Adjusted ORG US$ million STRATEGIC REPORT 02 Chairmans Statement 04 Our Stakeholders 06 Chief Executive Officers Strategic Report 10 888's B2C Proposition 12 Our Products on the Spotlight 14 Chief Financial Officer's Report 20 Risk Management Strategy 30 Regulation an

In [84]:
# Least important sentences
[(x,y) for y, x in sorted(zip(similarities, sentences), reverse=False)]

[('In addition to scheduled meetings, ORG met with the Chief Financial Officer and the internal and external auditors on a number of occasions',
  array([[-0.1801534]], dtype=float32)),
 ('When employees needed to be in our offices, all spaces were thoroughly cleaned and sanitised',
  array([[-0.17421038]], dtype=float32)),
 ('We work with partners in various areas of our business',
  array([[-0.16018352]], dtype=float32)),
 ('We work with partners in various areas of our business',
  array([[-0.16018352]], dtype=float32)),
 ('Meeting with internal and external auditors, both with and in the absence of ORG',
  array([[-0.1599888]], dtype=float32)),
 ('The partners responsible for the external audit are Angelique Linares, a partner in EYs Gibraltar office, and Philip Young, a partner in EYs London office',
  array([[-0.15573004]], dtype=float32)),
 ('Customer advances received are treated as deferred income within current liabilities and released as they are earned',
  array([[-0.153954